# Tasks for Zookeeper
# According to https://github.com/AnsibleShipyard/ansible-zookeeper
---
  - file: path=/opt/src state=directory
  - file: path={{ zookeeper_dir }} state=directory

  - name: Download Zookeeper
    get_url: url={{ zookeeper_url }} dest=/opt/src/zookeeper-{{ zookeeper_version }}.tar.gz
    when: "ansible_os_family == 'RedHat' and ansible_distribution_major_version == '7'"
    tags: zookeeper

  - name: Install OS packages
    yum: name={{ item }} state=present
    with_items:
      - libselinux-python
    when: "ansible_os_family == 'RedHat' and ansible_distribution_major_version == '7'"
    tags: zookeeper

  - name: Unpack Zookeeper tarball
    command: tar xzf /opt/src/zookeeper-{{ zookeeper_version }}.tar.gz --strip-components=1 chdir={{ zookeeper_dir }} creates={{ zookeeper_dir }}/bin
    when: "ansible_os_family == 'RedHat' and ansible_distribution_major_version == '7'"
    tags: zookeeper

  - name: Create zookeeper group
    group: name=zookeeper system=yes
    when: "ansible_os_family == 'RedHat' and ansible_distribution_major_version == '7'"
    tags: zookeeper

  - name: Create zookeeper user and add to zookeeper group
    user: name=zookeeper group=zookeeper system=yes
    when: "ansible_os_family == 'RedHat' and ansible_distribution_major_version == '7'"
    tags: zookeeper

  - name: Change ownership of Zookeeper directory
    file: path={{ zookeeper_dir }} state=directory owner=zookeeper recurse=yes
    when: "ansible_os_family == 'RedHat' and ansible_distribution_major_version == '7'"
    tags: zookeeper

  - name: Create Zookeeper data directory
    file: path={{ data_dir }} state=directory recurse=yes owner=zookeeper group=zookeeper
    when: "ansible_os_family == 'RedHat' and ansible_distribution_major_version == '7'"
    tags: zookeeper

  - name: Create Zookeeper log directory
    file: path={{ log_dir }} state=directory recurse=yes owner=zookeeper group=zookeeper
    when: "ansible_os_family == 'RedHat' and ansible_distribution_major_version == '7'"
    tags: zookeeper

  - name: Check if systemd exists
    stat: path=/usr/lib/systemd/system
    register: systemd_check
    when: "ansible_os_family == 'RedHat' and ansible_distribution_major_version == '7'"
    tags: zookeeper

  - name: Add systemd script template
    template: src=zookeeper.service.j2 dest=/usr/lib/systemd/system/zookeeper.service
    when: systemd_check.stat.exists == true and "ansible_os_family == 'RedHat' and ansible_distribution_major_version == '7'"
    notify:
      - Restart zookeeper
    tags: zookeeper

  - name: Write myid file
    template: src=myid.j2 dest={{ data_dir }}/myid owner=zookeeper group=zookeeper
    notify:
      - Restart zookeeper
    when: "ansible_os_family == 'RedHat' and ansible_distribution_major_version == '7'"
    tags: zookeeper

  - name: Configure Zookeeper
    template: src=zoo.cfg.j2 dest={{ zookeeper_dir }}/conf/zoo.cfg owner=zookeeper group=zookeeper
    notify:
      - Restart zookeeper
    when: "ansible_os_family == 'RedHat' and ansible_distribution_major_version == '7'"
    tags: zookeeper

  - name: Start Zookeeper service
    service: name=zookeeper state=started
    when: "ansible_os_family == 'RedHat' and ansible_distribution_major_version == '7'"
    tags: zookeeper
